apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: payment-config 
  
data: 
  config.yaml: |
    env: local

    server:
      address: ":8084"

    orders:
      url: "http://orders-service:8083"

    stripe:
      base_url: "https://api.stripe.com"
      success_url: "http://localhost:5173/payment/success"
      cancel_url: "http://localhost:5173/payment/cancel"

    db:
      host: postgres-service
      port: 5432
      user: postgres
      dbname: payment_db

    jwt:

    kafka: 
      address: "kafka-service:9092"
      topic: "payment-success"