apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config

data:
  config.yaml: |
    env: local

    server:
      address: ":8080"

    db:
      host: postgres-service
      port: 5432
      user: postgres
      dbname: vehicle_management

    jwt:
      access_expiry: 15m
      refresh_expiry: 168h