apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: default
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      volumes:
        - name: auth-config
          configMap:
            name: auth-config
      containers:
        - name: auth-container
          image: shivakumar2006/fletops-auth:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: auth-config
              mountPath: /app/config
          env:
            - name: CONFIG_PATH
              value: /app/config/config.yaml
