FROM golang:1.26.1-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . . 

RUN go build -o payment cmd/main.go
#runtime

FROM alpine:3.22

WORKDIR /app

COPY --from=builder /app/payment .

EXPOSE 8084

CMD ["/app/payment"]