FROM golang:1.26.1-alpine AS builder 

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download 

COPY . .

RUN go build -o inventory cmd/main.go 

# runtime 
FROM alpine:3.22

WORKDIR /app 

COPY --from=builder /app/inventory .

EXPOSE 8085

CMD ["/app/inventory"]