apiVersion: apps/v1
kind: Deployment
metadata: 
  name: vehicle-deployment
  namespace: default
  labels: 
    app: vehicle 
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: vehicle
  template:
    metadata:
      labels:
        app: vehicle 
    spec:
      containers:
        - name: vehicle-container
          image: shivakumar2006/feltops-vehicle:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: http 
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts: 
            - name: vehicle-config
              mountPath: /app/config
          env:
            - name: CONFIG_PATH
              value: /app/config/config.yaml
            
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vehicle-secret
                  key: DB_PASSWORD
            
            - name: JWT_ACCESS_SECRET 
              valueFrom: 
                secretKeyRef: 
                  name: vehicle-secret 
                  key: JWT_ACCESS_SECRET
            
            - name: JWT_REFRESH_SECRET
              valueFrom: 
                secretKeyRef: 
                  name: vehicle-secret 
                  key: JWT_REFRESH_SECRET

            - name: REDIS_PASSWORD 
              valueFrom: 
                secretKeyRef: 
                  name: vehicle-secret 
                  key: REDIS_PASSWORD
      volumes:
        - name: vehicle-config
          configMap:
            name: vehicle-config