apiVersion: v1 
kind: Secret 
metadata: 
  name: vehicle-secret

type: Opaque 

stringData: 
  DB_PASSWORD: "root"
  JWT_ACCESS_SECRET: "access-secret"
  JWT_REFRESH_SECRET: "refresh-secret"
  REDIS_PASSWORD: ""
  