FROM golang:1.26.1-alpine AS builder 

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o api_gateway cmd/main.go

# runtime
FROM alpine:3.22

WORKDIR /app

COPY --from=builder /app/api_gateway .

EXPOSE 8000

CMD ["/app/api_gateway"]